//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dunveler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dunveler.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] backrooms_atlas {
            get {
                object obj = ResourceManager.GetObject("backrooms_atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] backrooms_preview_tile {
            get {
                object obj = ResourceManager.GetObject("backrooms_preview_tile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clock_easy {
            get {
                object obj = ResourceManager.GetObject("clock_easy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clock_hard {
            get {
                object obj = ResourceManager.GetObject("clock_hard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clock_medium {
            get {
                object obj = ResourceManager.GetObject("clock_medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EASY.
        /// </summary>
        internal static string difficultyEasy {
            get {
                return ResourceManager.GetString("difficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARD.
        /// </summary>
        internal static string difficultyHard {
            get {
                return ResourceManager.GetString("difficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIUM.
        /// </summary>
        internal static string difficultyMedium {
            get {
                return ResourceManager.GetString("difficultyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon_atlas {
            get {
                object obj = ResourceManager.GetObject("dungeon_atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dungeon_preview_tile {
            get {
                object obj = ResourceManager.GetObject("dungeon_preview_tile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dunveler_icon {
            get {
                object obj = ResourceManager.GetObject("dunveler_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dunveler_logo_text {
            get {
                object obj = ResourceManager.GetObject("dunveler_logo_text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dunveler_logo_textshadow {
            get {
                object obj = ResourceManager.GetObject("dunveler_logo_textshadow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        internal static string helloWorldText {
            get {
                return ResourceManager.GetString("helloWorldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface scale:.
        /// </summary>
        internal static string interfaceScaleSettingsNameText {
            get {
                return ResourceManager.GetString("interfaceScaleSettingsNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface scale: .
        /// </summary>
        internal static string interfaceScaleText {
            get {
                return ResourceManager.GetString("interfaceScaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] interworld_atlas {
            get {
                object obj = ResourceManager.GetObject("interworld_atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] interworld_preview_tile {
            get {
                object obj = ResourceManager.GetObject("interworld_preview_tile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string mainMenuButtonExit {
            get {
                return ResourceManager.GetString("mainMenuButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        internal static string mainMenuButtonMainMenu {
            get {
                return ResourceManager.GetString("mainMenuButtonMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string mainMenuButtonPlay {
            get {
                return ResourceManager.GetString("mainMenuButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESUME.
        /// </summary>
        internal static string mainMenuButtonResume {
            get {
                return ResourceManager.GetString("mainMenuButtonResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string mainMenuButtonSettings {
            get {
                return ResourceManager.GetString("mainMenuButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] midasplace_atlas {
            get {
                object obj = ResourceManager.GetObject("midasplace_atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] midasplace_preview_tile {
            get {
                object obj = ResourceManager.GetObject("midasplace_preview_tile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mossy_atlas {
            get {
                object obj = ResourceManager.GetObject("mossy_atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mossy_preview_tile {
            get {
                object obj = ResourceManager.GetObject("mossy_preview_tile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pixelcyr_normal {
            get {
                object obj = ResourceManager.GetObject("pixelcyr_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pointerImg {
            get {
                object obj = ResourceManager.GetObject("pointerImg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string settingsButtonBack {
            get {
                return ResourceManager.GetString("settingsButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK &amp; APPLY.
        /// </summary>
        internal static string settingsButtonBackAndApply {
            get {
                return ResourceManager.GetString("settingsButtonBackAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is just the beginning....
        /// </summary>
        internal static string splashText {
            get {
                return ResourceManager.GetString("splashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vlad_atlas {
            get {
                object obj = ResourceManager.GetObject("vlad_atlas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vlad_preview_tile {
            get {
                object obj = ResourceManager.GetObject("vlad_preview_tile", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
